/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author mmanolas
 */
public class Main extends javax.swing.JFrame {
 javax.swing.JPopupMenu popupMenu;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

  public void createPopupMenu()
  {
    javax.swing.JMenuItem copy = new javax.swing.JMenuItem("copy");
    javax.swing.JMenuItem paste = new javax.swing.JMenuItem("paste");
    javax.swing.JMenuItem selectAll = new javax.swing.JMenuItem("select all");

    popupMenu = new javax.swing.JPopupMenu();
    popupMenu.add( copy );
    popupMenu.add( paste );
    popupMenu.add( selectAll );

    copy.addActionListener((ActionListener) this);
    paste.addActionListener((ActionListener) this);
    selectAll.addActionListener((ActionListener) this);
  }


  public void actionPerformed(java.awt.event.ActionEvent e)
  {
    String cmd = e.getActionCommand();

    if (cmd.equals("copy"))
    {
      lowerCase.copy();
    }
    else if (cmd.equals("paste"))
    {
      lowerCase.paste();
    }
    else if (cmd.equals("select all"))
    {
      lowerCase.selectAll();
    }
  }    
    
  class MouseHandler extends java.awt.event.MouseAdapter
{
  private javax.swing.JPopupMenu popupMenu;

  public MouseHandler(javax.swing.JPopupMenu popup)
  {
    this.popupMenu = popup;
  }

  public void mousePressed(java.awt.event.MouseEvent e)
  {
    if (e.isPopupTrigger())
      popupMenu.show(e.getComponent(), e.getX(), e.getY());
  }
            
  public void mouseReleased(java.awt.event.MouseEvent e )
  {
    if (e.isPopupTrigger())
      popupMenu.show(e.getComponent(), e.getX(), e.getY());
  }
            
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        strInput = new javax.swing.JTextField();
        lengthStr = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowerCase = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        upperCase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:: String to Lower & Upper Case ::.");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("String : ");

        strInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        strInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strInputActionPerformed(evt);
            }
        });
        strInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                strInputKeyTyped(evt);
            }
        });

        lengthStr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lengthStr.setText("Length : ");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lowerCase.setEditable(false);
        lowerCase.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        lowerCase.setColumns(20);
        lowerCase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lowerCase.setToolTipText(lowerCase.getText());
        lowerCase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lower Case", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        lowerCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lowerCaseMouseReleased(evt);
            }
        });
        lowerCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerCaseActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(lowerCase);

        upperCase.setEditable(false);
        upperCase.setBackground(new java.awt.Color(255, 255, 204));
        upperCase.setColumns(20);
        upperCase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upperCase.setToolTipText(upperCase.getText());
        upperCase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upper Case", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jScrollPane2.setViewportView(upperCase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lengthStr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(strInput, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(strInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(lengthStr)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(576, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void strInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strInputActionPerformed
        lowerCase.setText(strInput.getText().toLowerCase());
        upperCase.setText(strInput.getText().toUpperCase());
        lengthStr.setText("Length : "+strInput.getText().length());
    }//GEN-LAST:event_strInputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                lowerCase.setText(strInput.getText().toLowerCase());
        upperCase.setText(strInput.getText().toUpperCase());
        lengthStr.setText("Length : "+strInput.getText().length());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void strInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strInputKeyTyped
        lowerCase.setText(strInput.getText().toLowerCase());
        upperCase.setText(strInput.getText().toUpperCase());
        
        
        lengthStr.setText("Length : "+strInput.getText().length());
    }//GEN-LAST:event_strInputKeyTyped

    private void lowerCaseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowerCaseMouseReleased
        // TODO add your handling code here:
        //this.showpopup(evt);
    }//GEN-LAST:event_lowerCaseMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                   lowerCase.setText("\r");
        upperCase.setText("\r");
        strInput.setText("\r");
        lengthStr.setText("Length : 0"//+strInput.getText().length()
        );
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lowerCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerCaseActionPerformed
          String cmd = evt.getActionCommand();

    if (cmd.equals("copy"))
    {
      lowerCase.copy();
    }
    else if (cmd.equals("paste"))
    {
      lowerCase.paste();
    }
    else if (cmd.equals("select all"))
    {
      lowerCase.selectAll();
    }
    }//GEN-LAST:event_lowerCaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void mouseReleased(MouseEvent source) {
showpopup(source);
}
public void showpopup(MouseEvent source) {
        JPopupMenu popup = new JPopupMenu();
         popup.removeAll();
         JMenuItem menuItem = new JMenuItem("Copy");
         menuItem = new JMenuItem("Copy", KeyEvent.VK_C);
         menuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
         menuItem.setActionCommand(DefaultEditorKit.copyAction);
         popup.add(menuItem);
         menuItem = new JMenuItem("Paste");
         menuItem.setMnemonic(KeyEvent.VK_V);
         menuItem.setActionCommand(DefaultEditorKit.pasteAction);
         popup.add(menuItem);
         menuItem = new JMenuItem("Cut");
         menuItem.setActionCommand(DefaultEditorKit.cutAction);
         popup.add(menuItem);
         menuItem = new JMenuItem("SelectAll");
         menuItem.setActionCommand(DefaultEditorKit.selectAllAction);
         popup.add(menuItem);
         popup.show(source.getComponent(), source.getX(), source.getY());
       }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lengthStr;
    private javax.swing.JTextField lowerCase;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTextField strInput;
    private javax.swing.JTextField upperCase;
    // End of variables declaration//GEN-END:variables
}
